name: CI Maven build.

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Startup registry
      uses: addnab/docker-run-action@v3
      with:
        registry: docker.io
        image: registry:2
        options: --publish 5000:5000
      run: |
        docker pull docker.io/library/registry
        docker tag docker.io/library/registry localhost:5000/registry
        docker push localhost:5000/registry
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
